- name: Check if lazygit is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/lazygit
  register: lazygit_binary

- name: Get the latest lazygit release version
  when: lazygit_binary.stat.exists
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: yes
  register: lazygit_release

- name: Set lazygit version
  when: lazygit_binary.stat.exists
  set_fact:
    lazygit_version: "{{ lazygit_release.json.tag_name[1:] }}"

- name: Download lazygit tar.gz
  when: lazygit_binary.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/download/{{ lazygit_release.json.tag_name }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    dest: "/tmp/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    mode: '0755'

- name: Extract lazygit tar.gz
  when: lazygit_binary.stat.exists
  ansible.builtin.unarchive:
    src: "/tmp/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    dest: "/tmp"
  register: extract

- name: Install lazygit binary
  become: true
  ansible.builtin.command:
    cmd: install /tmp/lazygit /usr/local/bin/lazygit
  when: extract is changed and not lazygit_binary.stat.exists

